/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IGuardianControl,
  IGuardianControlInterface,
} from "../../../contracts/interfaces/IGuardianControl";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "newGuardian",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "oldGuardian",
        type: "address",
      },
    ],
    name: "GuardianSet",
    type: "event",
  },
];

export class IGuardianControl__factory {
  static readonly abi = _abi;
  static createInterface(): IGuardianControlInterface {
    return new utils.Interface(_abi) as IGuardianControlInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGuardianControl {
    return new Contract(address, _abi, signerOrProvider) as IGuardianControl;
  }
}
