/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as access from "./access";
export type { access };
import type * as ownable from "./ownable";
export type { ownable };
import type * as upgradeable from "./upgradeable";
export type { upgradeable };
