/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SoulWalletLogicTestAfter } from "./SoulWalletLogicTestAfter";
export type { SoulWalletLogicTestBefore } from "./SoulWalletLogicTestBefore";
