/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as logicUpgradeControlSol from "./logicUpgradeControl.sol";
export type { logicUpgradeControlSol };
export type { Initializable } from "./Initializable";
