/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as logicUpgradeControlSol from "./logicUpgradeControl.sol";
export { Initializable__factory } from "./Initializable__factory";
