/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as wethSol from "./WETH.sol";
export { SingletonFactory__factory } from "./SingletonFactory__factory";
